### ISSUE TITLE
PS4 needs to be updated ?

### ISSUE THREAD

**Issue by matteopiccioni** [theorywrong/ps4relink#2]
Hello,
to be able to use remote play, the PS4 needs to be updated to last firmware ? I am on 3.55

Thanks

**Comment by er388** [comment]
Yes. Remote Play on PS4 (regardless if you use PSV or PC) still relies on it being able to connect to PSN. You need latest firmware installed.

**Comment by matteopiccioni** [comment]
Thank you for answer
