### ISSUE TITLE
No longer working?

### ISSUE THREAD

**Issue by Aida-Enna** [theorywrong/ps4relink#3]
After I select to change the ID and reboot, no matter what I change it to, it's not different when I reload the program. I checked and it doesn't seem to be modifying the ur0:user/00/np/myprofile.dat file at all, the FTP is showing the same "last modified" before and after.

**Comment by Aida-Enna** [comment]
Doing it manually via the hexediting method worked too.

**Comment by Aida-Enna** [comment]
...but it changed back when it rebooted O_o

**Comment by ahjsrhj** [comment]
I have the same question, And I find just logout your psn from preferences setting. Then it will work
